services:
  db:
    image: postgres:14.7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quizapp
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
  backend:
    build: ./backend
    environment:
      PROJECT_NAME: quizapp
      POSTGRES_DB_URL: postgresql://postgres:postgres@db/quizapp
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
volumes:
  pgdata:
